--- #YAML:1.0
name:               Gearman-XS
version:            0.3
abstract:           This is a Perl front end for the Gearman C library. It aims to provide a simple interface closely tied to the C library
author:
    - Dennis Schoen <dennis@blogma.de>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Storable:    0
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
