---
abstract: 'Perl front end for the Gearman C library.'
author:
  - 'Data Differential, ala Brian Aker, http://datadifferential.com/'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Storable: 0
  Test::More: 0
configure_requires:
  ExtUtils::CBuilder: 0.27
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gearman-XS
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.14
